name: Pack

on:
  push:
    tags: v*

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108

    - name: Setup nuget
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: 'latest'

    - name: Build with dotnet
      run: dotnet build --configuration Release --verbosity diagnostic -p:PackageVersion=$(${Env:GITHUB_REF}.substring(11))

    - name: Test with nunit
      run: dotnet test --verbosity normal

    - name: Setup nuget config
      run: nuget.exe sources add -name github -source "https://nuget.pkg.github.com/apmem/index.json" -username ${{ github.actor }} -password ${{ secrets.GITHUB_TOKEN }}

    - name: Upload to GitHub Packages
      run: |
           for f in ./GodotAnalysers/GodotAnalysers.Package/bin/Release/*.nupkg
           do
             nuget push $f -Source "github"
           done
      shell: bash
